# SITE INFORMATION SETTINGS.
# Head info.
head:
  favicon: /img/favicon.svg
  high_res_favicon: /img/favicon.svg
  apple_touch_icon: /img/favicon.svg
  keywords: null
  site_verification:
    google: null
    baidu: null
  # Enable generate structured-data as JSON+LD for SEO or not.
  # Set as 'false' if it cause some wrong when `hexo g`.
  structured_data: true
# Jump link settings.
url:
  rss: null
  daily_pic: "#"
  logo: "#"

# STYLE SETTINGS.
# Scheme prefers.
scheme: Paradox
# scheme: Isolation
# UI & UX: slogan, color, effect.
uiux:
  slogan: 「自由的风终会吹动木讷的树」
  theme_color: "#0097A7"
  theme_sub_color: "#00838F"
  hyperlink_color: "#00838F"
  button_color: "#757575"
  android_chrome_color: "#0097A7"
  nprogress_color: "#29d"
  nprogress_buffer: "800"
# JS effect switches.
js_effect:
  fade: true
  smoothscroll: false
# Reading experience.
reading:
  entry_excerpt: 80
# Thumbnail settings.
thumbnail:
  purecolor: null
  random_amount: 5
# Background settings.
# bing available parameter:
# new | color= | type=.
# color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow.
# type available value: A (animal), C (culture), N (nature), S (space), T (travel).
background:
  purecolor: "#F5F5F5"
  # bgimg: "/img/bg.png"
  bing:
    enable: false
    parameter: null
# Images settings.
img:
  logo: /img/logo.webp
  avatar: /img/avatar.webp
  daily_pic: /img/daily_pic.webp
  sidebar_header: /img/sidebar_header.webp
  random_thumbnail: /img/random/windy-
  footer_image: null
# Custom fonts.
# family: the font-family which will be used in the theme.
# use: uri of fonts host.
# Available value: google | baomitu | ustc | custom | catnet.
# - When you set as 'custom', you should fill in the value of 'custom_font_host', which should be a mirror of google fonts.
# - If you have setup your custom font-family, don't forget to add style tag with @font-face or link.tag with font css
#   to /source/data/head.yml as custom code, to load custom font files.
fonts:
  family: Roboto, "Noto Sans CJK SC", "Helvetica Neue", Helvetica, "PingFang SC",
    "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
  use: baomitu
  custom_font_host: null
# Card elevation level.
card_elevation: 2
# Copyright.
# Specify the date when the site was setup.
# For example, if you set it as 2015, then footer will show '© 2015 - 2017'.
copyright_since: 2024
# Footer text.
# You can specify the text you want to show in footer, HTML tag is supported.
# For example, you can setup ICP license number as:
# '<a href="http://www.miitbeian.gov.cn" rel="nofollow">某ICP备xxxxxxxx号-x</a>'.
footer_text: null
# Qrcode for redirect at other device.
# use: choose which method to generate the qrcode for each posts.
# Available value: plugin | online.
# - When use "plugin", you need to install the hexo-helper-qrcode.
# - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
  enable: false
  use: plugin
# Code highlight.
# You can only enable one of them to avoid issues.
# Also you need to disable highlight option in hexo's _config.yml.
# Prettify.
# theme: # Available value in '/source/css/prettify/[theme].min.css'.
prettify:
  enable: false
  theme: github-v2
# Hanabi (https://github.com/egoist/hanabi).
# line_number: [true/false] # Show line number for code block.
# includeDefaultColors: [true/false] # Use default hanabi colors.
# customColors: This value accept a string or am array to setting for hanabi colors.
# - If `includeDefaultColors` is true, this will append colors to the color pool.
# - If `includeDefaultColors` is false, this will instead default color pool.
hanabi:
  enable: false
  line_number: true
  includeDefaultColors: true
  customColors: null
# Post license.
# You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
# For example, you can setup a CC license as:
# 'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'.
# You can also use Front-Matter `license` to override this setting.
license: null
# Gallery panel.
# You must activate Formspree before using.
gallery:
  panel_show: false
  left_show: true
  left_title: Introduction
  left_info: This is a Example.
  right_show: true
  right_title: Get in touch

# MENU SETTINGS.
# TOC button.
toc:
  # use: choose whether the line_number of toc will show or not.
  # Available value of "linenumber": true | false.
  linenumber: true
# SNS menu.
sns:
  email: breeze256@foxmail.com
  facebook: null
  twitter: null
  googleplus: null
  weibo: null
  instagram: null
  tumblr: null
  github: https://github.com/breeze256
  linkedin: null
  zhihu: null
  bilibili: https://space.bilibili.com/458140021
  telegram: null
  v2ex: null
  segmentfault: null
# SNS share switch.
sns_share:
  twitter: false
  facebook: false
  googleplus: false
  weibo: true
  linkedin: false
  qq: true
  telegram: false
# Sidebar customize.
sidebar:
  dropdown:
    Email Me:
      link: mailto:breeze256@foxmail.com
      icon: email
  homepage:
    use: true
    icon: home
    divider: false
  archives:
    use: true
    icon: inbox
    divider: false
  categories:
    use: true
    icon: chrome_reader_mode
    divider: false
  pages:
    标签:
      link: "/tags"
      icon: label
      divider: false
    关于:
      link: "/about"
      icon: info
      divider: false
  article_num:
    use: false
    divider: false
  footer:
    divider: true
    theme: true
    support: false
    feedback: false
    material: false

# INTERGRATED SERVICES
# Comment systems.
# Available value of "use":
# disqus | disqus_click | changyan | livere | gitment | gitalk | valine | wildfire.
# If you want to use gitment or gitalk, you should get the client_id and client_secret from https://github.com/settings/applications/new.
# If you want to use valine, you should get the app_id and app_key from https://leancloud.cn, more setting please see https://valine.js.org.
comment:
  use: gitalk
  gitalk_repo: breeze256.github.io # git repo of the hexo.
  gitalk_owner: breeze256 # git repo's owner.
  gitalk_client_id: Ov23liiaCOuM1ZnaIMWx # github app client id.
  gitalk_client_secret: a9b3c0d5e01003407e31f181ded0fe69f512f260 # github app client secret.
# Search Systems
# Available value:
# swiftype | google | local (HAVE ISSUE).
search:
  use: google
  swiftype_key: null
analytics:
  google_site_id: null
  baidu_site_id: null
  cnzz_site_id: null
# Leancloud views.
leancloud:
  enable: false
  app_id: null
  app_key: null
  av_core_mini: https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js
# Busuanzi views.
busuanzi:
  enable: false
  all_site_uv: false
  post_pv: false
  busuanzi_pure_mini_js: https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js
# MathJax.
mathjax:
  enable: true
# Files vendors.
# Set a CDN for the files src you want to customize. The url should with protocol.
# Default (empty) will load the files from the origin server.
vendors:
  materialcdn: null # decrypted.
  jquery: https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/jquery/3.5.1/jquery.js
  nprogress: https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/nprogress/0.2.0/nprogress.js
  fontawesome: https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css
  mathjax: https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/mathjax/2.7.9/MathJax.js
  prettify: https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/prettify/r298/prettify.min.js
  material_icons: https://cdn.jsdelivr.net/npm/material-icons@1.13.12/iconfont/material-icons.css
